from ImpararePackage import dataRequest
from multiprocessing import Pool, cpu_count
from ImpararePackage import maestro
import pandas as pd

def worker(c = pd.DataFrame):
    
    c = maestro.copy_columns(df= c, column= "atb")
    
    translate_atb = {
        #ACICLOVIR
        "ACICLOVIR 200MG COMP - ZOVIRAX" : "ACICLOVIR",
        "ACICLOVIR 400 MG COMP" : "ACICLOVIR",
        "ACICLOVIR 400MG COMP" : "ACICLOVIR",
        "ACICLOVIR (50MG/G) TB 10G CREME TOPICO - ZOVIRAX" : "ACICLOVIR",
        "ACICLOVIR FA 250MG PO LIOFILIZADO INJ - UNI VIR" : "ACICLOVIR",
        "ACICLOVIR FA 250MG PO LIOF INJ - UNI VIR" : "ACICLOVIR",
        #AMICACINA
        "AMICACINA - 100MG (50MG/ML) AMP 2ML INJ - AMICACINA" : "AMICACINA",
        "AMICACINA 500MG (250MG/ML) AMP 2ML INJ - AMICACINA" : "AMICACINA",
        #AMOX+CLAV
        "AMOXICIL+CLAVULAN (400MG+57MG/5ML) FR 70ML OR - CLAVULIN BD" : "AMOXICILINA_CLAVULANATO",
        "AMOXICILINA+CLAVULANAT (250MG+62,5MG/5ML) FR 75ML - CLAVULIN" : "AMOXICILINA_CLAVULANATO",
        "AMOXICILINA+CLAVULANATO 1G/200MG FA INJ - DOCLAXIN" : "AMOXICILINA_CLAVULANATO",
        "AMOXICILINA 500MG + CLAVULANATO 125MG COMP - CLAVULIN" : "AMOXICILINA_CLAVULANATO",
        "AMOXICILINA 500MG+ACIDO CLAVULANICO 125MG COMP - CLAVULIN BD" : "AMOXICILINA_CLAVULANATO",
        #AMOXICILINA
        "AMOXICILINA (250MG/5ML) FR 150ML PO SUS OR - AMOXIL" : "AMOXICILINA",
        "AMOXICILINA 500MG CAPS - AMOXIL" : "AMOXICILINA",
        #AMOXICILINA_SULBACTAM            
        "AMOXICILIN+SULBACT (200MG+50MG/ML) PO SUS FR 30ML - TRIFAMOX" : "AMOXICILINA_SULBACTAM",
        "AMOXI+SULBAC IBL BD 250MG/ML FR 30ML SUP - TRIFAMOX" : "AMOXICILINA_SULBACTAM",
        #AMPICILINA
        "AMPICILINA FA 1G PO INJ" : "AMPICILINA",
        #AMPICILINA_SULBACTAM
        "SULBACTAM 1,0G + AMPICILINA 2,0G PO INJ FA 3G" : "AMPICILINA_SULBACTAM",
        "SULBACTAM+AMPICILINA (0,5G+1,0G) FA 1,5G PO SOL INJ - UNASYN" : "AMPICILINA_SULBACTAM",
        #AZITROMICINA
        "AZITROMICINA 500MG COMP - ZITROMAX" : "AZITROMICINA",
        "AZITROMICINA 600MG (200MG/5ML) FR 15ML PO SUSP ORAL - ASTRO" : "AZITROMICINA",
        "AZITROMICINA 600MG (40MG/ML) FR 15ML PO SUSP OR - ASTRO" : "AZITROMICINA",
        "AZITROMICINA FA 500MG PO LIOF SOL INJ - ZITROMAX" : "AZITROMICINA",
        "INATIVO AZITROMICINA 600MG (200MG/5ML) FR 15ML PO SU - ASTRO" : "AZITROMICINA",
        #PENICILINAGBENZATINA
        "BENZILPENICILINA 1.200.000 (300.000U/ML) FA 4ML - BENZETACIL" : "PENICILINAGBENZATINA",
        "BENZILPENICILINA (300.000U/ML) FA 4ML SUSP INJ - BENZETACIL" : "PENICILINAGBENZATINA",
        "BENZILPENICILINA FA 400.000 UI PO INJ - PENKARON" : "PENICILINAGBENZATINA",
        #PENICILINAGPOTASSICA
        "PENICILINA  5.000.000UI INJ - ARICILINA" : "PENICILINAGPOTASSICA",
        "PENICILINA FA 5.000.000 UI PO INJ - ARICILINA" : "PENICILINAGPOTASSICA",
        #CEFADROXILA
        "CEFADROXILA (250MG/5ML) FR P/100ML PO SUSP ORAL" : "CEFADROXILA",
        "CEFADROXILA 500MG CAPS - CEFAMOX" : "CEFADROXILA",
        "CEFADROXILA (50MG/ML) FR 100ML PO SUSP ORAL" : "CEFADROXILA",
        #CEFALEXINA
        "CEFALEXINA 250MG/5ML (50MG/ML) FR 100ML SUSP ORAL - KEFLEX" : "CEFALEXINA",
        "CEFALEXINA 500MG COMP - KEFLEX " : "CEFALEXINA",
        "KEFLEX 250MG/5ML (50MG/ML) FR100ML SUSP ORAL - CEFALEXINA" : "CEFALEXINA",
        #CEFALOTINA
        "CEFALOTINA FA 1G PO SOL INJ - KEFLIN" : "CEFALOTINA",
        "KEFLIN FA 1G - CEFALOTINA" : "CEFALOTINA",
        #CEFAZOLINA
        "CEFAZOLINA FA 1G (1000MG) PO SOL INJ - KEFAZOL" : "CEFAZOLINA",
        "CEFAZOLINA SODICA 1G FR 1000MG (R) - KEFAZOL" : "CEFAZOLINA",
        #CEFOTAXIMA
        "CEFOTAXIMA SODICA 1G INJ - CLAFORDIL" : "CEFOTAXIMA",
        #CEFTAZIDIMA
        "CEFTAZIDIMA 1G FA PO INJ - CEFTAZIDON" : "CEFTAZIDIMA",
        "CEFTAZIDIMA FA 1G (1000MG) PO INJ - CEFTAZIDON" : "CEFTAZIDIMA",
        #CEFTAZIDIMA_AVIBACTAM
        "CEFTAZIDIMA 2000MG+AVIBACTAM 500MG FA 2.5G PO - TORGENA" : "CEFTAZIDIMA_AVIBACTAM",
        #CEFTALOZANA_TAZOBACTAM
        "CEFTOLOZANA 1G + TAZOBACTAM 0,5G - ZERBAXA TM" : "CEFTALOZANA_TAZOBACTAM",
        #CEFTRIAXONA
        "CEFTRIAXONA 1G FA 1000MG PO INJ IV (R) - ROCEFIN" : "CEFTRIAXONA",
        "CEFTRIAXONA FA 1G PO SOL INJ IM - ROCEFIN" : "CEFTRIAXONA",
        "CEFTRIAXONA FA 1G PO SOL INJ IV - ROCEFIN" : "CEFTRIAXONA",
        "CEFTRIAXONA FA 500MG PO SOL INJ IM - ROCEFIN" : "CEFTRIAXONA",
        #CEFUROXIMA
        "CEFUROXIMA FA 750MG PO INJ - ZINACEF" : "CEFUROXIMA",
        #CETOCONAZOL
        "CETOCONAZOL (20MG/G) TB 30G CREME - NIZORAL" : "CETOCONAZOL",
        #CIPROFLOXACINO
        "CIPROFLOXACINO 200MG (2MG/ML) BOLS 100ML INJ - FRESOFLOX" : "CIPROFLOXACINO",
        "CIPROFLOXACINO 200MG (2MG/ML) BS 100ML INJ - FRESOFLOX" : "CIPROFLOXACINO",
        "CIPROFLOXACINO 200MG (2MG/ML) BS 100ML INJ - HIFLOXAN" : "CIPROFLOXACINO",
        "CIPROFLOXACINO (3,5MG/ML) FR 5ML SOL OFT - CILOXAN" : "CIPROFLOXACINO",
        "CIPROFLOXACINO 400MG (2MG/ML) BOLS 200ML SOL INJ IV - CIPRO" : "CIPROFLOXACINO",
        "CIPROFLOXACINO 400MG (2MG/ML) FR 200ML SOL INJ IV - CIPRO" : "CIPROFLOXACINO",
        "CIPROFLOXACINO 500MG COMP REV - CIPRO" : "CIPROFLOXACINO",
        #CLARITROMICINA
        "CLARITROMICINA  500MG COMP - KLARICID" : "CLARITROMICINA",
        "CLARITROMICINA 500MG FA PO LIOF INJ - CLARILIB" : "CLARITROMICINA",
        #CLINDAMICINA
        "CLINDAMICINA 300MG CAPS DURA - DALACIN" : "CLINDAMICINA",
        "CLINDAMICINA 600MG (150MG/ML) AMP 4ML INJ - HYCLIN" : "CLINDAMICINA",
        #CEFEPIMA
        "CLORIDRATO CEFEPIMA FA 1G INJ - CLOCEF" : "CEFEPIMA",
        #DOXICICLINA
        "DOXICICLINA 100MG COMP REV - VIBRAMICINA " : "DOXICICLINA",
        "VIBRAMICINA 100MG COMP REV - DOXICICLINA" : "DOXICICLINA",
        #ERTAPENEM
        "ERTAPENEM FA 1G PO LIOF INJ - INVANZ" : "ERTAPENEM",
        #FLUCONAZOL
        "FLUCONAZOL 150MG CAPS DURA - ZOLTEC" : "FLUCONAZOL",
        "FLUCONAZOL 200MG (2MG/ML) BOLSA 100ML SOL INF - ZOLTEC" : "FLUCONAZOL",
        #GANCICLOVIR
        "GANCICLOVIR (1MG/ML) BOLS 500ML SOL IN PRONTO P/USO- CYMEVIR" : "GANCICLOVIR",
        "GANCICLOVIR 500MG PO FA LIOFILIZADO INJ - GANCICLOTRAT" : "GANCICLOVIR",
        "GANCICLOVIR 500MG SOL INJ BOLSA PRONTO P/ USO - CYMEVIR" : "GANCICLOVIR",
        "GANCICLOVIR FA 500MG PO LIOF INJ - GANCICLOTRAT" : "GANCICLOVIR",
        #GENTAMICINA
        "GENTAMICINA 20MG/1ML INJ - GENTAMICIN" : "GENTAMICINA",
        "GENTAMICINA 40MG (40MG/ML) AMP 1ML INJ - GARAMICINA" : "GENTAMICINA",
        "GENTAMICINA 80MG (40MG/ML) AMP 2ML INJ - GARAMICINA" : "GENTAMICINA",
        #IVERMECTINA
        "IVERMECTINA 6MG COMP - LEVERCTIN" : "IVERMECTINA",
        #ERITROMICINA
        "LACTOBIONATO ERITROMICINA FA 1000MG PO SOL INFUS - TROMAXIL" : "ERITROMICINA",
        #LEVOFLOXACINO
        "LEVOFLOXACINO 500MG (5MG/ML) BOLSA 100ML INJ - TAVANIC" : "LEVOFLOXACINO",
        "LEVOFLOXACINO 500MG COMP REV - LEVAQUIN" : "LEVOFLOXACINO",
        "LEVOFLOXACINO 750MG COMP REV - TAMIRAM" : "LEVOFLOXACINO",
        "LEVOFLOXACINO HEMI-HIDRATADO 750MG (5MG/ML) BOLSA 150ML" : "LEVOFLOXACINO",
        #LINEZOLIDA
        "LINEZOLIDA 600MG (2MG/ML) BOLSA 300ML SOL INF - ZYVOX" : "LINEZOLIDA",
        #MEROPENEM
        "MERONEM FA 1G (1000 MG) PO INJ - MEROPENEM" : "MEROPENEM",
        "MEROPENEM 1G FA 1000MG PO SOL INJ IV - MERONEM" : "MEROPENEM",
        "MEROPENEM FA 500MG PO SOL INJ - MERONEM" : "MEROPENEM",
        #METRONIDAZOL
        "METRONIDAZOL 250MG COMP - FLAGYL" : "METRONIDAZOL",
        "METRONIDAZOL 400MG COMP - FLAGYL" : "METRONIDAZOL",
        "METRONIDAZOL 500MG (5MG/ML) FR 100ML SOL INJ IV - FLAGYL" : "METRONIDAZOL",
        #MICAFUNGINA
        "MICAFUNGINA SODICA FA 100MG PO LIOF INF IV - MYCAMINE" : "MICAFUNGINA",
        "MICAFUNGINA SODICA FA 50MG PO LIOF INF IV - MYCAMINE" : "MICAFUNGINA",
        #MICONAZOL
        "DAKTARIN 20MG/G TB 40G GEL ORAL - MICONAZOL" : "MICONAZOL",
        "MICONAZOL (20MG/G) TB 40G GEL ORAL - DAKTARIN" : "MICONAZOL",
        #MOXIFLOXACINO
        "MOXIFLOXACINO 400MG (1,6MG/ML) BS 250ML SOL - AVALOX" : "MOXIFLOXACINO",
        "MOXIFLOXACINO 400MG COMP - AVALOX" : "MOXIFLOXACINO",
        "MOXIFLOXACINO (5,45MG/ML) FR 5ML SOL OFT - VIGAMOX" : "MOXIFLOXACINO",
        "MOXIFLOXACINO + FOSF DEXAMETASONA FR 5ML SOL OFT - VIGADEXA" : "MOXIFLOXACINO",
        "VIGAMOX 5,45MG/ML FR 5ML SOLUCAO OFTALMICA - MOXIFLOXACINO" : "MOXIFLOXACINO",
        #CLORANFENICOL
        "KOLLAGENASE + CLORANFENICOL TB 30G (CLORANFENICOL) " : "CLORANFENICOL",
        "RETINOL+AMINOAC+METIONINA+CLORANFE TB3,5G POM OFT - EPITEZAN" : "CLORANFENICOL",
        #MUPIROCINA
        "MUPIROCINA 2% (20MG/G) TB 15G POMADA - BACTROBAN" : "MUPIROCINA",
        #NEOMICINA
        "NEOMICINA+BACITRACINA (5MG+250UI/GR) TB 15G POM - NEBACETIN" : "NEOMICINA",
        "DEXAMETASONA+NEOMICINA+POLIMIXINA B FR 5ML SUSP OFT-MAXITROL" : "NEOMICINA",
        "TRIANCINOLONA+NEOMICINA+ASSOC TB 30G POMADA-OMCILON A M " : "NEOMICINA",
        #SULFADIAZINA
        "NITRATO CERIO 0,4%+SULFADIAZINA 1% TB 50G CREM - DERMACERIUM" : "SULFADIAZINA",
        "NITRATO CERIO 0,4%+SULFADIAZINA 1% TB 50G CREME-DERMACERIUM" : "SULFADIAZINA",
        "SULFADIAZINA PRATA (10MG/G) TB 50G CREME DERM - SILGLOS" : "SULFADIAZINA",
        "SULFADIAZINA PRATA 1% (10MG/GR) PT 400GR - DERMAZINE" : "SULFADIAZINA",
        "SULFADIAZINA PRATA 1% (10MG/GR) TB 30GR - DERMAZINE" : "SULFADIAZINA",
        #NISTATINA
        "NISTATINA100.000UI/ML FR 50ML SUSPENSAO ORAL - NEO MISTATIN" : "NISTATINA",
        "NISTATINA (100.000UI/ML) SER 10ML (R)" : "NISTATINA",
        "NISTATINA 100.000UI/ML SER 10ML (R)" : "NISTATINA",
        "NISTATINA CREME BISNAGA (25.000UI/G) TB 60G" : "NISTATINA",
        "NISTATINA 100000UI+OXIDO ZINCO 200MG/G TB 60G POM - DERMODEX" : "NISTATINA",
        #OXACILINA
        "OXACILINA SODICA FA 500MG PO SOL INJ - OXANON" : "OXACILINA",
        #PIPERACILINA_TAZOBACTAM
        "PIPERACILINA+TAZOBACTAM 2,25 (2G+250MG) PO LIO INJ - TAZOCIN" : "PIPERACILINA_TAZOBACTAM",
        "PIPERACILINA + TAZOBACTAM (4G/500MG) FA PO LIOF INJ -TAZOCIN" : "PIPERACILINA_TAZOBACTAM",
        #POLIMIXINAB
        "BEDFORDPOLY-B 500.000 UI PO LIOFILO INJ - POLIMIXINA B" : "POLIMIXINAB",
        "POLIMIXINA B BASE FA 500.000 UI PO LIOF INJ - BEDFORDPOLY-B" : "POLIMIXINAB",
        "POLIMIXINA B BASE FA 500.000 UI PO LIOF INJ - SPOX" : "POLIMIXINAB",
        #RIFAMPICINA
        "RIFAMPICINA 300MG CAPS DURA - RIFALDIN" : "RIFAMPICINA",
        #SULFAMETOXAZOL_TRIMETOPRIM
        "SULFAMETOXAZOL 400MG + TRIMETOPRIMA 80MG COMP - BACTRIM" : "SULFAMETOXAZOL_TRIMETOPRIM",
        "SULFAMETOXAZOL 800MG + TRIMETOPRIMA 160MG CAPS - BACTRIM" : "SULFAMETOXAZOL_TRIMETOPRIM",
        "SULFAMETOXAZOL 800MG + TRIMETOPRIMA 160MG COMP - BACTRIM" : "SULFAMETOXAZOL_TRIMETOPRIM",
        "SULFAMETOXAZOL+TRIMETOPRIM (200MG+40MG/5ML) FR 100ML BACTRIM" : "SULFAMETOXAZOL_TRIMETOPRIM",
        "SULFAMETOXAZ+TRIMETOPRIMA (400+80MG/5ML) INJ - BAC SULFITRIN" : "SULFAMETOXAZOL_TRIMETOPRIM",
        #TEICOPLANINA
        "TEICOPLANINA FA 200MG PO LIOF INJ - TARGOCID" : "TEICOPLANINA",
        "TEICOPLANINA FA 400MG PO LIOF INJ - TARGOCID" : "TEICOPLANINA",
        #TOBRAMICINA 
        "TOBRAMICINA (3MG/ML) FR 5ML SOL OFT - TOBREX" : "TOBRAMICINA",
        #VANCOMICINA
        "VANCOMICINA FA 500MG PO INJ - VANCOCINA" : "VANCOMICINA",
        #VORICONAZOL
        "VORICONAZOL 200MG COMP REV - VFEND" : "VORICONAZOL",
        "VORICONAZOL IV FR 200MG PO SOL INF - VFEND" : "VORICONAZOL",
        "VORICONAZOL IV FR 200MG PO SOL INF - VFEND IV" : "VORICONAZOL",
    }

    c["atb"] = c["atb"].apply(lambda x: translate_atb[str(x).strip().upper()] if str(x).upper().strip() in translate_atb.keys() else 'OUTRO')

    desejos = ['ACICLOVIR', 'AMICACINA', 'AMOXICILINA',
        'AMOXICILINA_CLAVULANATO', 'AMPICILINA', 'AMPICILINA_SULBACTAM', 'AMOXICILINA_SULBACTAM',
        'AZITROMICINA', 'CEFADROXILA','CEFALEXINA', 'CEFALOTINA',
        'CEFAZOLINA', 'CEFOTAXIMA', 'CEFEPIMA', 'CEFTAZIDIMA', 'CEFTAZIDIMA_AVIBACTAM',
        'CEFTRIAXONA', 'CEFTALOZANA_TAZOBACTAM', 'CEFUROXIMA', 'CETOCONAZOL', 'CLARITROMICINA',
        'CLINDAMICINA', 'CLORANFENICOL', 'DOXICICLINA', 'ERTAPENEM', 'ERITROMICINA', 'FLUCONAZOL',
        'GANCICLOVIR', 'GENTAMICINA', 'IVERMECTINA',
        'LEVOFLOXACINO', 'LINEZOLIDA', 'MEROPENEM', 'METRONIDAZOL',
        'MICAFUNGINA', 'MICONAZOL', 'MOXIFLOXACINO', 'MUPIROCINA', 'NISTATINA', 'NEOMICINA',
        'OXACILINA', 'PENICILINAGBENZATINA', 'PENICILINAGPOTASSICA',
        'PIPERACILINA_TAZOBACTAM', 'POLIMIXINAB',
        'RIFAMPICINA', 'SULFADIAZINA', 'SULFAMETOXAZOL_TRIMETOPRIM',
        'TEICOPLANINA', 'TOBRAMICINA', 'VANCOMICINA', 'VORICONAZOL',
        'CIPROFLOXACINO', 'OUTRO'
    ]
    c = maestro.create_dummy_vectorized(df= c,column= "atb", arrayDeDesejos= desejos)

    translate_via = {
        'VV': "EV",
        'EV': "EV",
        'IV': "EV",
        'EVB': "EV",
        'IN': "IM",
        'IM': "IM",
        'TO': "TOPICO",
        'OF': "TOPICO",
        'AO': "TOPICO",
        'HIP': "OUTRO",
        'SC': "OUTRO",
        'BE': "OUTRO",
        'JN': "OSTOMIA",
        'TQ': "OSTOMIA",
        'GT': "OSTOMIA",
        'SGA': "SNG",
        'SEN': "SNG",
        'VO': "VO",
    }
    c['via'] = c['via'].apply(lambda x: translate_via[str(x).strip().upper()] if str(x).strip().upper() in translate_via.keys() else "OUTRO")
    desejos = ['EV', 'IM', 'TOPICO', 'SNG', 'VO', 'OUTRO']
    c = maestro.create_dummy_vectorized(df= c,column= "via",  arrayDeDesejos= desejos)

    colunas = ["registro", "cd_pre_med"]
    c = maestro.to_int(df= c, arrayColumns= colunas)

    tuplas = [(",", ".")]
    c = maestro.replace_values_list(df= c, column= "dose", arrayDeTuplas= tuplas)

    colunas = [
        "prescription_date",
        "atb"
    ]
    c = maestro.remove_columns(df= c, arrayColumns= colunas)
    
    novosNomes = {
        "atb_copy": "atb",
    }
    c = maestro.rename_columns(df= c, DictColumns= novosNomes)

    dataRequest.set_data_on_sql(df= c, nomeTabelaDestino= "imparare2_prescricoesantibiotico_prepared", if_exists=  "append")

def main():
    replace =True
    if replace:
        create_query = """
            DROP TABLE IF EXISTS imparare2_prescricoesantibiotico_prepared;
            CREATE UNLOGGED TABLE IF NOT EXISTS imparare2_prescricoesantibiotico_prepared (
                registro INTEGER,
                cd_pre_med INTEGER,
                dthr_prescricao TIMESTAMP,
                atb TEXT NULL,
                dose TEXT NULL,
                unidade TEXT NULL,
                frequencia TEXT NULL,
                via TEXT NULL,
                "atb_ACICLOVIR" INTEGER NULL,
                "atb_AMICACINA" INTEGER NULL,
                "atb_AMOXICILINA" INTEGER NULL,
                "atb_AMOXICILINA_CLAVULANATO" INTEGER NULL,
                "atb_AMPICILINA" INTEGER NULL,
                "atb_AMPICILINA_SULBACTAM" INTEGER NULL,
                "atb_AMOXICILINA_SULBACTAM" INTEGER NULL,
                "atb_AZITROMICINA" INTEGER NULL,
                "atb_CEFADROXILA" INTEGER NULL,
                "atb_CEFALEXINA" INTEGER NULL,
                "atb_CEFALOTINA" INTEGER NULL,
                "atb_CEFAZOLINA" INTEGER NULL,
                "atb_CEFOTAXIMA" INTEGER NULL,
                "atb_CEFEPIMA" INTEGER NULL,
                "atb_CEFTAZIDIMA" INTEGER NULL,
                "atb_CEFTAZIDIMA_AVIBACTAM" INTEGER NULL,
                "atb_CEFTRIAXONA" INTEGER NULL,
                "atb_CEFTALOZANA_TAZOBACTAM" INTEGER NULL,
                "atb_CEFUROXIMA" INTEGER NULL,
                "atb_CETOCONAZOL" INTEGER NULL,
                "atb_CLARITROMICINA" INTEGER NULL,
                "atb_CLINDAMICINA" INTEGER NULL,
                "atb_CLORANFENICOL" INTEGER NULL,
                "atb_DOXICICLINA" INTEGER NULL,
                "atb_ERTAPENEM" INTEGER NULL,
                "atb_ERITROMICINA" INTEGER NULL,
                "atb_FLUCONAZOL" INTEGER NULL,
                "atb_GANCICLOVIR" INTEGER NULL,
                "atb_GENTAMICINA" INTEGER NULL,
                "atb_IVERMECTINA" INTEGER NULL,
                "atb_LEVOFLOXACINO" INTEGER NULL,
                "atb_LINEZOLIDA" INTEGER NULL,
                "atb_MEROPENEM" INTEGER NULL,
                "atb_METRONIDAZOL" INTEGER NULL,
                "atb_MICAFUNGINA" INTEGER NULL,
                "atb_MICONAZOL" INTEGER NULL,
                "atb_MOXIFLOXACINO" INTEGER NULL,
                "atb_MUPIROCINA" INTEGER NULL,
                "atb_NISTATINA" INTEGER NULL,
                "atb_NEOMICINA" INTEGER NULL,
                "atb_OXACILINA" INTEGER NULL,
                "atb_PENICILINAGBENZATINA" INTEGER NULL,
                "atb_PENICILINAGPOTASSICA" INTEGER NULL,
                "atb_PIPERACILINA_TAZOBACTAM" INTEGER NULL,
                "atb_POLIMIXINAB" INTEGER NULL,
                "atb_RIFAMPICINA" INTEGER NULL,
                "atb_SULFADIAZINA" INTEGER NULL,
                "atb_SULFAMETOXAZOL_TRIMETOPRIM" INTEGER NULL,
                "atb_TEICOPLANINA" INTEGER NULL,
                "atb_TOBRAMICINA" INTEGER NULL,
                "atb_VANCOMICINA" INTEGER NULL,
                "atb_VORICONAZOL" INTEGER NULL,
                "atb_CIPROFLOXACINO" INTEGER NULL,
                "atb_OUTRO" INTEGER NULL,
                "via_EV" INTEGER NULL,
                "via_IM" INTEGER NULL,
                "via_TOPICO" INTEGER NULL,
                "via_SNG" INTEGER NULL,
                "via_VO" INTEGER NULL,
                "via_OUTRO" INTEGER NULL,
                attendance_type TEXT NULL
            );
            """
        dataRequest.execute(queryText= create_query)

    append_query = """
        SELECT
            registro AS registro,
            MAX("CD_PRE_MED") AS cd_pre_med,
            prescription_date AS dthr_prescricao,
            atb AS atb,
            MAX("DOSE")::text AS dose,
            MAX("UNID") AS unidade,
            MAX("FREQUENCIA") AS frequencia,
            MAX("VIA") AS via,
            'I' AS attendance_type
        FROM(
            SELECT
                record_id AS registro,
                FIRST_VALUE(pre_med_id) OVER (PARTITION BY record_id, prescription_date, antibiotic ORDER BY prescription_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "CD_PRE_MED",
                prescription_date AS prescription_date,
                antibiotic AS atb,
                FIRST_VALUE(dosage) OVER (PARTITION BY record_id, prescription_date, antibiotic ORDER BY prescription_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "DOSE",
                FIRST_VALUE(antibiotic_unity) OVER (PARTITION BY record_id, prescription_date, antibiotic ORDER BY prescription_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "UNID",
                FIRST_VALUE(frequency) OVER (PARTITION BY record_id, prescription_date, antibiotic ORDER BY prescription_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "FREQUENCIA",
                FIRST_VALUE(via) OVER (PARTITION BY record_id, prescription_date, antibiotic ORDER BY prescription_date ASC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "VIA"            
            FROM prescriptions
        ) p
        GROUP BY "registro", "prescription_date", "atb";
    """

    df_iterator = dataRequest.get_data(queryText= append_query, chunck = 2000)
    with Pool(processes= cpu_count()) as pool:
        for _ in pool.imap_unordered(worker, df_iterator):
            pass

if __name__ == "__main__":
    main()